/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import code.Player;
import java.util.Scanner;

/**
 *
 * @author crist
 */
public class Playboard extends javax.swing.JFrame {
    int[][] playBoard = new int[4][4];
    Player player1 = new Player(askName(), 1, playBoard);
    Player player2 = new Player(askName(), 2, playBoard);
    /**
     * Creates new form Playboard
     */
    public Playboard() {
        initComponents();
        placeShips(player1);
        placeShips(player2);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPlayBoard = new javax.swing.JPanel();
        jButtonPlace1 = new javax.swing.JButton();
        jButtonPlace2 = new javax.swing.JButton();
        jButtonPlace3 = new javax.swing.JButton();
        jButtonPlace4 = new javax.swing.JButton();
        jButtonPlace5 = new javax.swing.JButton();
        jButtonPlace6 = new javax.swing.JButton();
        jButtonPlace7 = new javax.swing.JButton();
        jButtonPlace8 = new javax.swing.JButton();
        jButtonPlace9 = new javax.swing.JButton();
        jButtonPlace10 = new javax.swing.JButton();
        jButtonPlace11 = new javax.swing.JButton();
        jButtonPlace12 = new javax.swing.JButton();
        jButtonPlace13 = new javax.swing.JButton();
        jButtonPlace14 = new javax.swing.JButton();
        jButtonPlace15 = new javax.swing.JButton();
        jButtonPlace16 = new javax.swing.JButton();
        jButtonRestart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelPlayBoard.setLayout(new java.awt.GridLayout(4, 4, 1, 1));

        jButtonPlace1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlace1ActionPerformed(evt);
            }
        });
        jPanelPlayBoard.add(jButtonPlace1);

        jButtonPlace2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlace2ActionPerformed(evt);
            }
        });
        jPanelPlayBoard.add(jButtonPlace2);

        jButtonPlace3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlace3ActionPerformed(evt);
            }
        });
        jPanelPlayBoard.add(jButtonPlace3);

        jButtonPlace4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlace4ActionPerformed(evt);
            }
        });
        jPanelPlayBoard.add(jButtonPlace4);

        jButtonPlace5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlace5ActionPerformed(evt);
            }
        });
        jPanelPlayBoard.add(jButtonPlace5);

        jButtonPlace6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlace6ActionPerformed(evt);
            }
        });
        jPanelPlayBoard.add(jButtonPlace6);

        jButtonPlace7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlace7ActionPerformed(evt);
            }
        });
        jPanelPlayBoard.add(jButtonPlace7);

        jButtonPlace8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlace8ActionPerformed(evt);
            }
        });
        jPanelPlayBoard.add(jButtonPlace8);

        jButtonPlace9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlace9ActionPerformed(evt);
            }
        });
        jPanelPlayBoard.add(jButtonPlace9);

        jButtonPlace10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlace10ActionPerformed(evt);
            }
        });
        jPanelPlayBoard.add(jButtonPlace10);

        jButtonPlace11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlace11ActionPerformed(evt);
            }
        });
        jPanelPlayBoard.add(jButtonPlace11);

        jButtonPlace12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlace12ActionPerformed(evt);
            }
        });
        jPanelPlayBoard.add(jButtonPlace12);

        jButtonPlace13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlace13ActionPerformed(evt);
            }
        });
        jPanelPlayBoard.add(jButtonPlace13);

        jButtonPlace14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlace14ActionPerformed(evt);
            }
        });
        jPanelPlayBoard.add(jButtonPlace14);

        jButtonPlace15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlace15ActionPerformed(evt);
            }
        });
        jPanelPlayBoard.add(jButtonPlace15);

        jButtonPlace16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlace16ActionPerformed(evt);
            }
        });
        jPanelPlayBoard.add(jButtonPlace16);

        jButtonRestart.setText("Restart");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPlayBoard, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRestart, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelPlayBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRestart, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPlace1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlace1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPlace1ActionPerformed

    private void jButtonPlace2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlace2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPlace2ActionPerformed

    private void jButtonPlace3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlace3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPlace3ActionPerformed

    private void jButtonPlace4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlace4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPlace4ActionPerformed

    private void jButtonPlace5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlace5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPlace5ActionPerformed

    private void jButtonPlace6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlace6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPlace6ActionPerformed

    private void jButtonPlace7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlace7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPlace7ActionPerformed

    private void jButtonPlace8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlace8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPlace8ActionPerformed

    private void jButtonPlace9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlace9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPlace9ActionPerformed

    private void jButtonPlace10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlace10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPlace10ActionPerformed

    private void jButtonPlace11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlace11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPlace11ActionPerformed

    private void jButtonPlace12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlace12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPlace12ActionPerformed

    private void jButtonPlace13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlace13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPlace13ActionPerformed

    private void jButtonPlace14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlace14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPlace14ActionPerformed

    private void jButtonPlace15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlace15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPlace15ActionPerformed

    private void jButtonPlace16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlace16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPlace16ActionPerformed
    
    void placeShips(Player player) {
        Scanner sc = new Scanner(System.in);
        int[][] boardPlaceShips = player.getPlayBoard();
        int totalShip = player.getPlayBoard().length, i = 1;
        System.out.println("Place your ships, saying the coordinates");
        while(totalShip > 0) {
            System.out.println("Ship number "+i+" row");
            int positionRow = sc.nextInt();
            System.out.println("Ship number "+i+" column");
            int positionColumn = sc.nextInt();
            boardPlaceShips[positionRow][positionColumn] = 1;
            totalShip--;
            i++;
        }
    }
    
    String askName() {
        Scanner sc = new Scanner(System.in);
        System.out.println("Please, enter your name");
        return sc.next();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Playboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Playboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Playboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Playboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Playboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPlace1;
    private javax.swing.JButton jButtonPlace10;
    private javax.swing.JButton jButtonPlace11;
    private javax.swing.JButton jButtonPlace12;
    private javax.swing.JButton jButtonPlace13;
    private javax.swing.JButton jButtonPlace14;
    private javax.swing.JButton jButtonPlace15;
    private javax.swing.JButton jButtonPlace16;
    private javax.swing.JButton jButtonPlace2;
    private javax.swing.JButton jButtonPlace3;
    private javax.swing.JButton jButtonPlace4;
    private javax.swing.JButton jButtonPlace5;
    private javax.swing.JButton jButtonPlace6;
    private javax.swing.JButton jButtonPlace7;
    private javax.swing.JButton jButtonPlace8;
    private javax.swing.JButton jButtonPlace9;
    private javax.swing.JButton jButtonRestart;
    private javax.swing.JPanel jPanelPlayBoard;
    // End of variables declaration//GEN-END:variables

}
